//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YG35426_MadameMarie.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetail = new HashSet<OrderDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<bool> isDelivered { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
        public Nullable<int> ShipCity { get; set; }
        public Nullable<int> ShipTown { get; set; }
        public string ShipAddress { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> InvoiceID { get; set; }
    
        public virtual City City { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual Town Town { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
    }
}
